### ISSUE TITLE
Restrict keyspace

### ISSUE THREAD

**Issue by OevreFlataeker** [sebastien-riou/aes-brute-force#1]
Is there a way to restrict the key space it is going to test? As far as I understand it tests for every key byte all possible combinations from 0x00-0xff. I would like to change this to e.g. only UPPERCASE characters (0x41-0x5A). In my case the key is not derived from the plaintext password, but key==password and I know some characters of it. So the key is 16 bytes in the range of 0x41-0x5a. How to specify this? Thanks!

**Comment by sebastien-riou** [comment]
I added a way to specify the valid range for bytes, see https://github.com/sebastien-riou/aes-brute-force/blob/master/test_range.sh

**Comment by OevreFlataeker** [comment]
Merci beaucoup, cela a fonctionné parfaitement! :-D
