### ISSUE TITLE
New byte range function segfaults on some systems

### ISSUE THREAD

**Issue by OevreFlataeker** [sebastien-riou/aes-brute-force#2]
aes-brute-force on some systems when using the latest "restrict keybytes" feature:

`
./test_range.sh 

INFO: 144 concurrent threads supported in hardware.

Search parameters:
                n_threads:    144
                key_mask:     000000FF_00000000_FF000000_FF0000FF
                key_in:       41424300_45464748_004A4B4C_004E4F00
                plain:        3243F6A8_885A308D_313198A2_E0370734
                cipher:       CB1D0839_594405D8_E9BB8EAE_2483A8CC
                byte_min:     0x41
                byte_max:     0x5A

                jobs_key_mask:00000000_00000000_FF000000_FF0000FF

./test_range.sh: line 9: 49369 Segmentation fault      (core dumped) `

CPU details:

`
lscpu

Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                144
On-line CPU(s) list:   0-143
Thread(s) per core:    2
Core(s) per socket:    18
Socket(s):             4
NUMA node(s):          4
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 79
Model name:            Intel(R) Xeon(R) CPU E7-8867 v4 @ 2.40GHz
Stepping:              1
CPU MHz:               2394.082
CPU max MHz:           3300.0000
CPU min MHz:           1200.0000
BogoMIPS:              4788.16
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              46080K
NUMA node0 CPU(s):     0-17,72-89
NUMA node1 CPU(s):     18-35,90-107
NUMA node2 CPU(s):     36-53,108-125
NUMA node3 CPU(s):     54-71,126-143
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single pti intel_ppin ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap intel_pt xsaveopt cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts flush_l1d `

It works without problems on a less powerful home server system:

`lscpu

Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    1
Core(s) per socket:    4
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 58
Model name:            Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz
Stepping:              9
CPU MHz:               1752.750
CPU max MHz:           3600.0000
CPU min MHz:           1600.0000
BogoMIPS:              6385.79
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              6144K
NUMA node0 CPU(s):     0-3
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm epb ssbd ibrs ibpb stibp kaiser tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm ida arat pln pts flush_l1d
`

Running aes-brute-force w/o test data works without problems:

`./aes-brute-force 
AES128 encryption key brute force search
Usage: ./aes-brute-force <key_mask> <key_in> <plain> <cipher> [byte_min] [byte_max] [n_threads]

launching test/demo...

./aes-brute-force FF0000FF_00FF0000_0000FF00_00000000 007E1500_2800D2A6_ABF70088_09CF4F3C 3243F6A8_885A308D_313198A2_E0370734 3925841D_02DC09FB_DC118597_196A0B32 

INFO: 144 concurrent threads supported in hardware.

Search parameters:
                n_threads:    144
                key_mask:     FF0000FF_00FF0000_0000FF00_00000000
                key_in:       007E1500_2800D2A6_ABF70088_09CF4F3C
                plain:        3243F6A8_885A308D_313198A2_E0370734
                cipher:       3925841D_02DC09FB_DC118597_196A0B32
                byte_min:     0x00
                byte_max:     0xFF

                jobs_key_mask:000000FF_00FF0000_0000FF00_00000000

Launching 32 bits search
This can take a couple of minutes on slow computers.

Thread 21 claims to have found the key
                key found:    2B7E1516_28AED2A6_ABF71588_09CF4F3C

Performances:
                4760275448 AES128 operations done in 7.28767s
                1ns per AES128 operation
                653.20 million keys per second
INFO: found the expected key, test passed.`

**Comment by sebastien-riou** [comment]
thanks for testing on a powerful computer! Indeed the first attempt does not handle well cases with limited range and high number of threads. I am going to do something cleaner and more effecient. meanwhile you can add a number of thread as last argument, it seems the maximum viable currently is 16 for the byte range that you target.

**Comment by sebastien-riou** [comment]
I do not have a 144 cores machine to test, but the latest commit will most likely resolve the issue.

**Comment by OevreFlataeker** [comment]
Merci Sebastien for the latest fix! It works like a charm! It is almost about twice the speed as before!
This one was on a 144 core machine.

Thread 116 claims to have found the key
	key found:   XXXX_XXXX_XXXX_XXXX

Performances:
	85266275329 AES128 operations done in 66.2994s
	0ns per AES128 operation
	1286.08 million keys per second


It was NOT needed to specify the number of threads!
This is really awesome!

If I could ask for another feature - if you can spare the time. It would be super-flexible if there was an option where you could actually specify the keybyte values to use. 0x41 - 0x5d is for example the uppercase ASCII range. Maybe you want to do uppercase and lowercase - which cannot be specified continuously. And I don't always have a 144 core machine at hand to just include the bytes in between. Maybe the bytes to use could be specified as a single param like --bytes-to-use 41424344451889fa0a1a2a3a etc. for 0x41, 0x42, 0x43, 0x44, 0x45, 0x18, 0x89, 0xfa,0x0a,0x1a,0x2a,0xa3a or somthing like that. This would be really cool! Thank you again for this great tool!

**Comment by sebastien-riou** [comment]
Thanks for testing and reporting back the performances on that beast. I created a new issue for your feature request. There is a clear path to support it, just need some spare time...
