### ISSUE TITLE
arbitrary restriction on the set of possible byte values

### ISSUE THREAD

**Issue by sebastien-riou** [sebastien-riou/aes-brute-force#3]
It would be super-flexible if there was an option where you could actually specify the keybyte values to use. 0x41 - 0x5d is for example the uppercase ASCII range. Maybe you want to do uppercase and lowercase - which cannot be specified continuously. And I don't always have a 144 core machine at hand to just include the bytes in between. Maybe the bytes to use could be specified as a single param like --bytestouse 4142434451889fa0a1a2a3 etc. for 0x41, 0x42, 0x43, 0x44, 0x45, 0x18, 0x89,0xfa,0x0a,0xa1,0xa2,0xa3, etc. 

_Originally posted by @OevreFlataeker in https://github.com/sebastien-riou/aes-brute-force/issues/2#issuecomment-490455604_

**Comment by sebastien-riou** [comment]
implemented, see test_restricted.sh and "usage 2" of command line, make sure the bytes are sorted in ascending order.

**Comment by OevreFlataeker** [comment]
Works perfectly! Thank you!
